### ISSUE TITLE
Problem with substation and floating

### ISSUE THREAD

**Issue by jcs19570124** [alexbodogit/AnchorageFX#19]
I have a problem with substation. 
I first put a dock of the substation in floating mode. And when i want to put into the substation again, the dock disappears.

Thanks for your code.

**Comment by alexbodogit** [comment]
Ok post your code and i will fix it 😉

**Comment by jcs19570124** [comment]
Here is my code

```
    package demo_for_testing;
    ..

    /**
     * 
     */
    public class AnchorFX_substations_floating extends Application {


        @Override
        public void start(Stage primaryStage) {

            DockNode node1, subNode, subNode2;
            DockSubStation station1;

            DockStation station = AnchorageSystem.createStation();

            Scene scene = new Scene(station, 1024, 768);

            node1 = AnchorageSystem.createDock("Node", new TableView<>());
            node1.dock(station, DockNode.DockPosition.CENTER);

            station1 = AnchorageSystem.createSubStation(station, "SubStation");
            station1.dock(station, DockNode.DockPosition.LEFT);

            subNode = AnchorageSystem.createDock("subNode 1", builtPane());
            subNode.dock(station1, DockNode.DockPosition.LEFT);

            subNode2 = AnchorageSystem.createDock("subNode 2", builtPane());
            subNode2.dock(station1, DockNode.DockPosition.LEFT);

            AnchorageSystem.installDefaultStyle();

            primaryStage.setTitle("Test");
            primaryStage.setScene(scene);
            primaryStage.show();

        }

        private AnchorPane builtPane() {
            AnchorPane anchorPane = new AnchorPane();
            Label label=new Label("First make this node floating.\n" +
                    "Then try to dock it. \n" +
                    "The node disappears");
            anchorPane.getChildren().add(label);
            AnchorPane.setTopAnchor(label,0.0);
            AnchorPane.setRightAnchor(label,0.0);
            AnchorPane.setBottomAnchor(label,0.0);
            AnchorPane.setLeftAnchor(label,0.0);
            anchorPane.setStyle("-fx-background-color: ALICEBLUE");
            return anchorPane;
        }

        public static void main(String[] args) {
            launch(args);
        }
    }
```

I have also this error 
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
    at com.anchorage.docks.containers.zones.DockZones.makePreview(DockZones.java:389)
    at com.anchorage.docks.containers.zones.DockZones.searchArea(DockZones.java:261)
    at com.anchorage.docks.stations.DockStation.searchTargetNode(DockStation.java:159)
    at com.anchorage.system.AnchorageSystem.searchTargetNode(AnchorageSystem.java:106)
    at com.anchorage.docks.node.ui.DockUIPanel.manageDragEvent(DockUIPanel.java:151)
    at com.anchorage.docks.node.ui.DockUIPanel.lambda$installDragEventMananger$1(DockUIPanel.java:120)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:352)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:275)
    at java.security.AccessController.doPrivileged(Native Method)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:388)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:387)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
    at com.sun.glass.ui.View.notifyMouse(View.java:937)

**Comment by jcs19570124** [comment]
Hello, 
I think i have solve the problem. I am not an expert in javafx and my code is certainly not the best.

I add two methods for docking after floating.

```
public void dock_AfterFloatting(DockStation station, DockPosition position) {
  //  if (stationProperty().get() != null) {
  //      ensureVisibility();
  //      return;
  //  }

  //  station.add(this);
    station.putDock(this, position, 0.5);
    this.station.set((DockStation) station);
}
public void dock_AfterFloatting(DockNode nodeTarget, DockPosition position) {
  //        System.out.println("public void dock(DockNode nodeTarget, DockPosition position) {");
  //        if (stationProperty().get() != null) {
  //            ensureVisibility();
  //            return;
  //        }

    nodeTarget.stationProperty().get().add(this);
    nodeTarget.getParentContainer().putDock(this, nodeTarget, position, 0.5);
    station.set(nodeTarget.station.get());
}
```
