### ISSUE TITLE
Moving DockNodes does not work under Linux

### ISSUE THREAD

**Issue by xylo** [alexbodogit/AnchorageFX#28]
I discovered a strange behavior when I try to drag a DockNode.  First, a window is created and dragged with the mouse movement (which I expect to be intended).  But after around 100 ms this window get stuck.  It does not follow the mouse anymore and it does not respond to any event.  I cannot even close the extracted window anymore and it keeps staying on top of all windows when I switch to another application window.

My system is a 64 bit Linux system with a Kernel 3.13.0-100-generic running in a virtual machine (via VirtualBox).
Here's my java version:
```
java version "1.8.0_111"
Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
```

**Comment by xylo** [comment]
During one of my tests I got also this exception, but somehow I doubt that it's related since it appeared only once:

```
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.anchorage.docks.containers.zones.DockZones.makePreview(DockZones.java:385)
	at com.anchorage.docks.containers.zones.DockZones.searchArea(DockZones.java:257)
	at com.anchorage.docks.stations.DockStation.searchTargetNode(DockStation.java:159)
	at com.anchorage.system.AnchorageSystem.searchTargetNode(AnchorageSystem.java:106)
	at com.anchorage.docks.node.ui.DockUIPanel.manageDragEvent(DockUIPanel.java:153)
	at com.anchorage.docks.node.ui.DockUIPanel.lambda$installDragEventMananger$1(DockUIPanel.java:122)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jotomo** [comment]
This might be a more general JavaFX issues as FxDock has the same problem. DockFX also suffers from this, but there the window starts moving again for a second every five seconds are so.
Using OpenJDK 1.8.0.112 on Arch Linux (4.8.13), with an intel integrated GPU (but I thing I also saw this with my nvidia GPU).

**Comment by m-radzikowski** [comment]
I also have this issue. I was surprised, as on the Windows there is no problem.

```
Linux Mint 18.1 Serena
kernel 4.4.0-53-generic

java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) 64-Bit Server VM (build 25.144-b01, mixed mode)
```

**Comment by roeibit** [comment]
Anything new about this issue? 
AnchorFx moving dock functionally just doesn't work under linux.
